### PR TITLE
Provide support for 4.10 kernels on earlier Fedora releases

### PR DESCRIPTION
**Pull request by stevestorey**

### CODE REVIEW

**Comment by scaronni** [comment]
Hello, thanks for the patch! I would have merged it as is, but I decided to use the Ubuntu patches which do not patch the UVM files, so I can keep the SPEC file a bit simpler.

**Comment by stevestorey** [comment]
Sure - thanks for all the hard work keeping this updated!

**Comment by pstrangwrzekle** [comment]
Any pointers how to get nvidia-driver-375.39-1.el7.x86_64 (from http://negativo17.org/repos/nvidia/epel-7/x86_64/) working in kernel-ml-4.10.0-1.el7.elrepo.x86_64?
Thanks for the help!

**Comment by scaronni** [comment]
Just install <code>dkms-nvidia kernel-devel</code> in place of <code>kmod-nvidia</code>.

The module will be autobuilt with DKMS instead of relying on the pre-built kABI module.

**Comment by pstrangwrzekle** [comment]
Thx, but I've been running like that for a while now.  Kernel 4.10 won't boot X.  I'll research more and post the exact errors:

[~]$ rpm -qa |grep -i nvidia
dkms-nvidia-375.39-1.el7.x86_64
nvidia-driver-cuda-libs-375.39-1.el7.x86_64
nvidia-persistenced-375.39-1.el7.x86_64
nvidia-driver-375.39-1.el7.x86_64
nvidia-settings-375.39-1.el7.x86_64
nvidia-driver-libs-375.39-1.el7.i686
nvidia-driver-NVML-375.39-1.el7.x86_64
nvidia-libXNVCtrl-375.39-1.el7.x86_64
nvidia-driver-cuda-375.39-1.el7.x86_64
nvidia-driver-libs-375.39-1.el7.x86_64

**Comment by scaronni** [comment]
Ah, OK, sorry. I did not apply the patch for kernel 4.10 on the long lived releases. Patches for unsupported kernels usually go into Fedora, mainly the rawhide branch; as for RHEL normally people do not update the kernel (what's the point of that? Then use Fedora :) ).

You might want to apply this patch from Fedora:

https://github.com/negativo17/nvidia-kmod/blob/master/kernel_4.10.patch

I'll make an update that contains the patch in the next days also for RHEL.

**Comment by pstrangwrzekle** [comment]
Right, that's probably the issue.  At home I run Fedora, but at work they want me to run RHEL because they have a support contract.  But I usually keep the kernel updated.  Actually, the default RHEL7 kernel won't even boot on my docking station, so I'm forced to use updated kernels.

Thanks again for your support and hard work to keep negativo17 repos updated.  You're providing a great service to the community!  :)

**Pull request closed without merging**
